[package]
name = "t2_flex"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[profile.release]
#opt-level = "z"
debug = 0
panic = "abort"

[dependencies]
